<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="5" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-17T17:42:44 IST" name="Suite" finished-at="2022-08-17T17:42:52 IST" duration-ms="8535">
    <groups>
      <group name="regression">
        <method signature="a1.M1()[pri:0, instance:Test_NG.a1@a530d0a]" name="M1" class="Test_NG.a1"/>
      </group> <!-- regression -->
    </groups>
    <test started-at="2022-08-17T17:42:44 IST" name="Test" finished-at="2022-08-17T17:42:52 IST" duration-ms="8535">
      <class name="Test_NG.a1">
        <test-method is-config="true" signature="BM()[pri:0, instance:Test_NG.a1@a530d0a]" started-at="2022-08-17T17:42:44 IST" name="BM" finished-at="2022-08-17T17:42:49 IST" duration-ms="5237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BM -->
        <test-method signature="M1()[pri:0, instance:Test_NG.a1@a530d0a]" started-at="2022-08-17T17:42:49 IST" name="M1" finished-at="2022-08-17T17:42:49 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- M1 -->
        <test-method is-config="true" signature="AM()[pri:0, instance:Test_NG.a1@a530d0a]" started-at="2022-08-17T17:42:49 IST" name="AM" finished-at="2022-08-17T17:42:49 IST" duration-ms="198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AM -->
        <test-method is-config="true" signature="BM()[pri:0, instance:Test_NG.a1@a530d0a]" started-at="2022-08-17T17:42:49 IST" name="BM" finished-at="2022-08-17T17:42:51 IST" duration-ms="1218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BM -->
        <test-method signature="M2()[pri:0, instance:Test_NG.a1@a530d0a]" started-at="2022-08-17T17:42:51 IST" name="M2" finished-at="2022-08-17T17:42:51 IST" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Test_NG.a1.M2(a1.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- M2 -->
        <test-method is-config="true" signature="AM()[pri:0, instance:Test_NG.a1@a530d0a]" started-at="2022-08-17T17:42:51 IST" name="AM" finished-at="2022-08-17T17:42:51 IST" duration-ms="255" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AM -->
        <test-method is-config="true" signature="BM()[pri:0, instance:Test_NG.a1@a530d0a]" started-at="2022-08-17T17:42:51 IST" name="BM" finished-at="2022-08-17T17:42:52 IST" duration-ms="1296" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BM -->
        <test-method signature="M4()[pri:0, instance:Test_NG.a1@a530d0a]" started-at="2022-08-17T17:42:52 IST" name="M4" finished-at="2022-08-17T17:42:52 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- M4 -->
        <test-method is-config="true" signature="AM()[pri:0, instance:Test_NG.a1@a530d0a]" started-at="2022-08-17T17:42:52 IST" name="AM" finished-at="2022-08-17T17:42:52 IST" duration-ms="229" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AM -->
      </class> <!-- Test_NG.a1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
